export interface HisGuide {
  menu: string          // เมนูหลักใน HIS
  path: string[]        // เส้นทางเมนู
  screen: string        // หน้าจอที่ต้องใช้
  note?: string         // หมายเหตุเพิ่มเติม
  keyFields: string[]   // ฟิลด์สำคัญที่ต้องตรวจสอบใน HIS
}

// คู่มือเมนู HIS สำหรับแต่ละแฟ้ม 43 แฟ้มมาตรฐาน (HOSxP / EHP CIS)
const HIS_GUIDE: Record<string, HisGuide> = {
  PERSON: {
    menu: 'งานทะเบียน',
    path: ['งานทะเบียนผู้ป่วยนอก', 'ลงทะเบียนผู้ป่วย'],
    screen: 'หน้าจอลงทะเบียนผู้ป่วย / ข้อมูลทั่วไป',
    note: 'ตรวจสอบข้อมูลส่วนตัวให้ครบถ้วน',
    keyFields: ['CID - เลขบัตรประชาชน 13 หลัก', 'NAME/LNAME - ชื่อ-นามสกุล', 'BIRTH - วันเกิด (YYYYMMDD)', 'SEX - เพศ (1=ชาย, 2=หญิง)', 'TYPEAREA - สถานะบุคคล', 'PRENAME - คำนำหน้า', 'NATION - รหัสสัญชาติ'],
  },
  ADDRESS: {
    menu: 'งานทะเบียน',
    path: ['งานทะเบียนผู้ป่วยนอก', 'ลงทะเบียนผู้ป่วย', 'แท็บที่อยู่'],
    screen: 'ข้อมูลที่อยู่ผู้ป่วย',
    note: 'กรอกที่อยู่ให้ครบทุกระดับ',
    keyFields: ['VILLAGE - รหัสหมู่ที่', 'TAMBON - รหัสตำบล', 'AMPUR - รหัสอำเภอ', 'CHANGWAT - รหัสจังหวัด', 'ADDRESSTYPE - ประเภทที่อยู่', 'D_UPDATE - วันที่อัปเดต'],
  },
  DEATH: {
    menu: 'งานทะเบียน / งาน PP',
    path: ['งานทะเบียนผู้ป่วยนอก', 'บันทึกการเสียชีวิต'],
    screen: 'บันทึกข้อมูลการเสียชีวิต',
    note: 'ระบุสาเหตุการตายตาม ICD-10',
    keyFields: ['DDEATH - วันที่เสียชีวิต (YYYYMMDD)', 'CDEATH - รหัสสาเหตุการตาย (ICD-10)', 'CDEATH_A ถึง D - สาเหตุอื่น', 'PDEATH - สถานที่ตาย (1=รพ., 2=บ้าน)', 'DATE_DEAD - วันที่บันทึก'],
  },
  CHRONIC: {
    menu: 'งาน NCD / โรคเรื้อรัง',
    path: ['งานผู้ป่วยนอก', 'ข้อมูล NCD', 'ทะเบียนโรคเรื้อรัง'],
    screen: 'บันทึกโรคเรื้อรัง',
    note: 'ลงทะเบียนโรคเรื้อรังในหน้า NCD',
    keyFields: ['CHRONIC_CODE - รหัสโรคเรื้อรัง (ICD-10)', 'DATE_DIAG - วันที่วินิจฉัย', 'TYPEDX - ประเภทการวินิจฉัย', 'CLINIC - คลินิกที่ดูแล'],
  },
  CARD: {
    menu: 'งานทะเบียน',
    path: ['งานทะเบียนผู้ป่วยนอก', 'ลงทะเบียนผู้ป่วย', 'แท็บสิทธิ'],
    screen: 'ข้อมูลสิทธิการรักษา (บัตรทอง/ประกัน)',
    note: 'อัปเดตสิทธิการรักษาให้เป็นปัจจุบัน',
    keyFields: ['INSCL - ประเภทสิทธิ (UC=บัตรทอง, SSS=ประกันสังคม)', 'INSTYPE - ประเภทประกัน', 'DATEEXP - วันหมดอายุสิทธิ (YYYYMMDD)', 'SUBINSCL - สิทธิย่อย', 'HOSPMAIN - รหัสสถานพยาบาลหลัก'],
  },
  HOME: {
    menu: 'งาน PP / งานชุมชน',
    path: ['งาน PCU', 'สำรวจข้อมูลครัวเรือน'],
    screen: 'บันทึกข้อมูลครัวเรือน',
    note: 'สำรวจและบันทึกข้อมูลบ้านประจำปี',
    keyFields: ['HOUSENO - บ้านเลขที่', 'HTYPE - ประเภทที่อยู่อาศัย', 'WATER - แหล่งน้ำดื่ม', 'LATRINE - ส้วม', 'GARBAGE - การกำจัดขยะ', 'HOWNER - เจ้าของบ้าน'],
  },
  VILLAGE: {
    menu: 'งาน PP / งานชุมชน',
    path: ['งาน PCU', 'ข้อมูลหมู่บ้าน/ชุมชน'],
    screen: 'ตั้งค่าข้อมูลหมู่บ้าน',
    note: 'บันทึกข้อมูลชุมชน/หมู่บ้านให้ครบ',
    keyFields: ['VILLCODE - รหัสหมู่บ้าน', 'VILLNAME - ชื่อหมู่บ้าน', 'NUMHEAD - จำนวนหลังคาเรือน', 'NUMMEM - จำนวนสมาชิก', 'NUMHOME - จำนวนบ้าน'],
  },
  DISABILITY: {
    menu: 'งาน PP / งานชุมชน',
    path: ['งาน PCU', 'ทะเบียนคนพิการ'],
    screen: 'บันทึกข้อมูลผู้พิการ',
    note: 'ลงทะเบียนผู้พิการพร้อมประเภทและระดับ',
    keyFields: ['DISABTYPE - ประเภทความพิการ (1-6)', 'DISABLEVEL - ระดับความพิการ', 'DISABDATE - วันที่ขึ้นทะเบียน', 'DISABCARD - เลขบัตรคนพิการ'],
  },
  PROVIDER: {
    menu: 'ตั้งค่าระบบ',
    path: ['ตั้งค่า', 'ข้อมูลบุคลากร / ผู้ให้บริการ'],
    screen: 'ทะเบียนบุคลากร',
    note: 'ลงทะเบียนบุคลากรให้ครบถ้วน',
    keyFields: ['PROVIDER - รหัสบุคลากร (13 หลัก)', 'PROVNAME - ชื่อบุคลากร', 'PROVTYPE - ประเภทบุคลากร', 'LICENCENO - ใบประกอบวิชาชีพ', 'CLINIC - คลินิกที่ดูแล'],
  },
  WOMEN: {
    menu: 'งาน PP / อนามัยแม่และเด็ก',
    path: ['งาน PCU', 'ทะเบียนหญิงวัยเจริญพันธุ์'],
    screen: 'บันทึกหญิงวัยเจริญพันธุ์',
    note: 'บันทึกสถานะหญิงวัยเจริญพันธุ์',
    keyFields: ['FPCURRUSE - วิธีคุมกำเนิด (0=ไม่ใช้, 1-9=วิธีต่างๆ)', 'MARRYSTATUS - สถานภาพสมรส', 'FPSTATUS - สถานะการคุมกำเนิด'],
  },
  DRUGALLERGY: {
    menu: 'งานผู้ป่วยนอก / งานทะเบียน',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'ประวัติแพ้ยา'],
    screen: 'บันทึกประวัติการแพ้ยา',
    note: 'บันทึกประวัติแพ้ยาทุกครั้งที่ตรวจพบ',
    keyFields: ['DCODE - รหัสยาที่แพ้', 'ATYPE - ประเภทอาการแพ้', 'DATE_ALLERGY - วันที่ตรวจพบ', 'ALRGTYPE - ประเภทการแพ้ (1=แน่นอน, 2=สงสัย)'],
  },
  FUNCTIONAL: {
    menu: 'งาน PP / งานผู้สูงอายุ',
    path: ['งาน PCU', 'ประเมินความบกพร่องทางสุขภาพ'],
    screen: 'แบบประเมิน ADL / Barthel Index',
    note: 'ประเมิน ADL ในผู้สูงอายุ/ผู้พิการ',
    keyFields: ['FUNCTYPE - ประเภทการประเมิน', 'ADL - คะแนน Barthel Index (0-20)', 'DATE_ASSESS - วันที่ประเมิน'],
  },
  ICF: {
    menu: 'งาน PP / งานผู้พิการ',
    path: ['งาน PCU', 'ประเมิน ICF'],
    screen: 'แบบประเมิน ICF',
    note: 'ประเมินระดับสุขภาพตาม ICF',
    keyFields: ['ICFCODE - รหัส ICF', 'ICFLEVEL - ระดับความสามารถ (0-4)', 'DATE_ASSESS - วันที่ประเมิน'],
  },
  SERVICE: {
    menu: 'งานผู้ป่วยนอก',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'ข้อมูลการมารับบริการ'],
    screen: 'บันทึก OPD Visit',
    note: 'บันทึกทุกครั้งที่ผู้ป่วยมารับบริการ',
    keyFields: ['DATE_SERV - วันที่รับบริการ', 'SEQ - เลข visit', 'VERC - รหัสเหตุที่มา (1=เดินมาเอง, 2=นัด)', 'PTTYPE - ประเภทผู้ป่วย/สิทธิ', 'CLINIC - คลินิก', 'PROVIDER - แพทย์/ผู้ให้บริการ'],
  },
  SURVEILLANCE: {
    menu: 'งาน PP / เฝ้าระวังโรค',
    path: ['งาน PCU', 'บันทึกเฝ้าระวังโรค'],
    screen: 'บันทึกข้อมูลเฝ้าระวังโรค',
    note: 'บันทึกผู้ป่วยโรคที่ต้องรายงาน',
    keyFields: ['DISEASE_CODE - รหัสโรค (ICD-10)', 'DATE_SICK - วันที่ป่วย', 'DATE_DIAG - วันที่วินิจฉัย', 'SEVERITY - ความรุนแรง'],
  },
  ACCIDENT: {
    menu: 'งานห้องฉุกเฉิน (ER)',
    path: ['งานผู้ป่วยนอก', 'ER/อุบัติเหตุ', 'บันทึกอุบัติเหตุฉุกเฉิน'],
    screen: 'บันทึกข้อมูลอุบัติเหตุฉุกเฉิน',
    note: 'บันทึกครบทุก field ของอุบัติเหตุ',
    keyFields: ['DATE_SERV - วันที่รับ', 'AEPLACE - สถานที่เกิดเหตุ (01=บ้าน...99=ไม่ทราบ)', 'TYPEIN_AE - ประเภทการมา (1=เดินมาเอง, 2=ส่งต่อ)', 'URGENCY - ระดับฉุกเฉิน (1-4)', 'ALCOHOL - ดื่มแอลกอฮอล์ (1=ใช่, 2=ไม่, 9=ไม่ทราบ)', 'AIRWAY/STOPBLEED/SPLINT/FLUID - การรักษา'],
  },
  LABFU: {
    menu: 'งานห้องปฏิบัติการ',
    path: ['งานผู้ป่วยนอก', 'บันทึกผลแล็บ / LAB'],
    screen: 'บันทึกผลการตรวจทางห้องปฏิบัติการ',
    note: 'บันทึกผลแล็บพร้อมค่าอ้างอิง',
    keyFields: ['LABTEST - รหัสการทดสอบ', 'LABRESULT - ผลการตรวจ', 'LABNORMAL - ค่าอ้างอิงปกติ', 'UNIT - หน่วย', 'DATE_EXAM - วันที่ตรวจ'],
  },
  CHRONICFU: {
    menu: 'งาน NCD / คลินิกโรคเรื้อรัง',
    path: ['งานผู้ป่วยนอก', 'คลินิกโรคเรื้อรัง', 'ติดตามผู้ป่วย NCD'],
    screen: 'บันทึกการติดตามโรคเรื้อรัง',
    note: 'บันทึกผลการติดตาม DM/HT ทุกครั้ง',
    keyFields: ['CHRONIC_CODE - รหัสโรค', 'DATE_SERV - วันที่ติดตาม', 'CLINIC - คลินิก', 'RESULT - ผลการตรวจ'],
  },
  ADMISSION: {
    menu: 'งานผู้ป่วยใน (IPD)',
    path: ['งานผู้ป่วยใน', 'รับผู้ป่วยใน', 'ข้อมูล Admission'],
    screen: 'บันทึก IPD Admission',
    note: 'บันทึก Admission และ Discharge ให้ครบ',
    keyFields: ['AN - เลขที่ผู้ป่วยใน (9 หลัก)', 'WARDADMIT - แผนกที่รับ', 'DATETIME_ADMIT - วันเวลารับ (YYYYMMDDHHMMSS)', 'DATETIME_DISCH - วันเวลาจำหน่าย', 'DISCHSTATUS - สถานภาพจำหน่าย', 'DISCHTYPE - วิธีจำหน่าย'],
  },
  DIAGNOSIS_OPD: {
    menu: 'งานผู้ป่วยนอก',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'วินิจฉัยโรค'],
    screen: 'บันทึกการวินิจฉัยโรค OPD',
    note: 'ระบุรหัส ICD-10 ให้ถูกต้อง',
    keyFields: ['DIAGCODE - รหัส ICD-10 (ต้องมีจุดทศนิยม)', 'DXTYPE - ประเภท (01=โรคหลัก, 02=โรคร่วม)', 'DATE_DIAG - วันที่วินิจฉัย'],
  },
  DIAGNOSIS_IPD: {
    menu: 'งานผู้ป่วยใน (IPD)',
    path: ['งานผู้ป่วยใน', 'บันทึก IPD', 'วินิจฉัยโรค'],
    screen: 'บันทึกการวินิจฉัยโรค IPD',
    note: 'ระบุ Principal/Secondary Diagnosis',
    keyFields: ['AN - เลขที่ผู้ป่วยใน', 'DIAGCODE - รหัส ICD-10', 'DXTYPE - ประเภทการวินิจฉัย'],
  },
  DRUG_OPD: {
    menu: 'งานผู้ป่วยนอก / งานเภสัช',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'สั่งยา'],
    screen: 'บันทึกการสั่งยา OPD',
    note: 'ตรวจสอบรหัสยาและจำนวนให้ถูกต้อง',
    keyFields: ['DIDCODE - รหัสยา (24 FC)', 'DNAME - ชื่อยา', 'AMOUNT - จำนวน', 'UNIT - หน่วย', 'DRUGPRICE - ราคา', 'SIGCODE - วิธีใช้'],
  },
  DRUG_IPD: {
    menu: 'งานผู้ป่วยใน / งานเภสัช',
    path: ['งานผู้ป่วยใน', 'บันทึก IPD', 'สั่งยา'],
    screen: 'บันทึกการสั่งยา IPD',
    note: 'ตรวจสอบรหัสยาและ AN ให้ถูกต้อง',
    keyFields: ['AN - เลขที่ผู้ป่วยใน', 'DIDCODE - รหัสยา', 'AMOUNT - จำนวน', 'UNIT - หน่วย'],
  },
  PROCEDURE_OPD: {
    menu: 'งานผู้ป่วยนอก',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'หัตถการ'],
    screen: 'บันทึกหัตถการ OPD',
    note: 'ระบุรหัส ICD-9-CM ให้ถูกต้อง',
    keyFields: ['PROCEDCODE - รหัส ICD-9-CM', 'PROCEDTYPE - ประเภทหัตถการ', 'DATE_SERV - วันที่ทำหัตถการ'],
  },
  PROCEDURE_IPD: {
    menu: 'งานผู้ป่วยใน (IPD)',
    path: ['งานผู้ป่วยใน', 'บันทึก IPD', 'หัตถการ'],
    screen: 'บันทึกหัตถการ IPD',
    note: 'ระบุรหัส ICD-9-CM และ AN ให้ถูกต้อง',
    keyFields: ['AN - เลขที่ผู้ป่วยใน', 'PROCEDCODE - รหัส ICD-9-CM', 'PROCEDTYPE - ประเภทหัตถการ'],
  },
  CHARGE_OPD: {
    menu: 'งานการเงิน / งานผู้ป่วยนอก',
    path: ['งานผู้ป่วยนอก', 'บันทึก OPD', 'ค่าบริการ'],
    screen: 'บันทึกค่าบริการ OPD',
    note: 'ตรวจสอบรหัสรายการค่าบริการ',
    keyFields: ['CHRGITEM - รหัสรายการ (CF)', 'AMOUNT - จำนวน', 'COST - ราคาทุน', 'PRICE - ราคาขาย'],
  },
  CHARGE_IPD: {
    menu: 'งานการเงิน / งานผู้ป่วยใน',
    path: ['งานผู้ป่วยใน', 'บันทึก IPD', 'ค่าบริการ'],
    screen: 'บันทึกค่าบริการ IPD',
    note: 'ตรวจสอบรหัสรายการและ AN',
    keyFields: ['AN - เลขที่ผู้ป่วยใน', 'CHRGITEM - รหัสรายการ', 'AMOUNT - จำนวน', 'COST - ราคาทุน'],
  },
  APPOINTMENT: {
    menu: 'งานนัดหมาย',
    path: ['งานผู้ป่วยนอก', 'นัดหมาย / คิวนัด'],
    screen: 'บันทึกการนัดหมาย',
    note: 'บันทึกนัดหมายให้ครบทุก field',
    keyFields: ['APTYPE - ประเภทนัด (1=follow up, 2=นัดใหม่)', 'APDATE - วันนัด (YYYYMMDD)', 'APTIME - เวลานัด', 'CLINIC - คลินิก', 'PROVIDER - แพทย์นัด'],
  },
  DENTAL: {
    menu: 'งานทันตกรรม',
    path: ['งานทันตกรรม', 'บันทึกทันตกรรม'],
    screen: 'บันทึกข้อมูลทันตกรรม',
    note: 'บันทึกสภาพฟันและการรักษา',
    keyFields: ['TNTYPE - ประเภทงานทันตกรรม', 'TEETH - ซี่ฟัน (FDI notation)', 'RDCODE - รหัสการรักษา', 'DATE_SERV - วันที่รักษา'],
  },
  REHABILITATION: {
    menu: 'งานกายภาพบำบัด',
    path: ['งานผู้ป่วยนอก', 'กายภาพบำบัด / ฟื้นฟูสมรรถภาพ'],
    screen: 'บันทึกการฟื้นฟูสมรรถภาพ',
    note: 'บันทึกประเภทและเป้าหมายการฟื้นฟู',
    keyFields: ['REHABTYPE - ประเภทการฟื้นฟู', 'REHABILITTYPE - วิธีการ', 'TARGET - เป้าหมาย', 'DATE_SERV - วันที่'],
  },
  NCDSCREEN: {
    menu: 'งาน PP / คัดกรอง NCD',
    path: ['งาน PCU', 'คัดกรองโรคไม่ติดต่อ', 'บันทึกผลคัดกรอง NCD'],
    screen: 'บันทึกผลคัดกรอง DM/HT',
    note: 'บันทึกผลคัดกรองตามกลุ่มเป้าหมาย',
    keyFields: ['GLUCOSETYPE - ประเภทน้ำตาล (1=FBS, 2=OGTT, 3=HbA1c)', 'GLUCOSE_RESULT - ผลน้ำตาล', 'BP_SYSTOLIC - ความดันบน', 'BP_DIASTOLIC - ความดันล่าง', 'WEIGHT/HEIGHT/WAIST - ข้อมูลร่างกาย'],
  },
  FP: {
    menu: 'งาน PP / อนามัยเจริญพันธุ์',
    path: ['งาน PCU', 'วางแผนครอบครัว'],
    screen: 'บันทึกการวางแผนครอบครัว',
    note: 'บันทึกวิธีคุมกำเนิดที่ใช้',
    keyFields: ['FPCURRUSE - วิธีคุมกำเนิด (1=ยา, 2=ถุงยาง, ...9=ไม่ใช้)', 'FPREASON - เหตุผล', 'DATE_SERV - วันที่'],
  },
  PRENATAL: {
    menu: 'งาน PP / ฝากครรภ์',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ฝากครรภ์ครั้งแรก'],
    screen: 'บันทึกฝากครรภ์ครั้งแรก (ANC First Visit)',
    note: 'บันทึกเมื่อมาฝากครรภ์ครั้งแรก',
    keyFields: ['GRAVIDA - จำนวนครรภ์', 'PARA - จำนวนคลอด', 'LMP - ประจำเดือนครั้งสุดท้าย', 'EDC - กำหนดคลอด (YYYYMMDD)', 'FOLICACID - ได้รับโฟลิก (1=ใช่, 2=ไม่)'],
  },
  ANC: {
    menu: 'งาน PP / ฝากครรภ์',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ฝากครรภ์แต่ละครั้ง'],
    screen: 'บันทึกฝากครรภ์ (ANC Each Visit)',
    note: 'บันทึกทุกครั้งที่มาฝากครรภ์',
    keyFields: ['ANCNO - ครั้งที่ฝากครรภ์', 'GESTAGE - อายุครรภ์ (สัปดาห์)', 'BPCHECK - ความดัน', 'WEIGHT - น้ำหนัก', 'FH - ระยะมดลูก (ซม.)', 'FETALMOVEMENT - ดิ้น'],
  },
  LABOR: {
    menu: 'งาน PP / ห้องคลอด',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'บันทึกการคลอด'],
    screen: 'บันทึกข้อมูลการคลอด',
    note: 'บันทึกหลังคลอดทุกราย',
    keyFields: ['LABORTYPE - ประเภทการคลอด (1=ปกติ, 2=ผ่าคลอด)', 'PLACETYPE - สถานที่คลอด', 'LABORTIME - เวลาคลอด', 'BABYSEX - เพศทารก', 'BIRTHWEIGHT - น้ำหนักทารก (กรัม)'],
  },
  POSTNATAL: {
    menu: 'งาน PP / หลังคลอด',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ดูแลหลังคลอด'],
    screen: 'บันทึกการดูแลหลังคลอด',
    note: 'บันทึกการเยี่ยมหลังคลอด 3 ครั้ง',
    keyFields: ['PNVISITNO - ครั้งที่เยี่ยม (1-3)', 'DATE_SERV - วันที่เยี่ยม', 'BREASTFEED - ให้นมแม่ (1=ใช่)', 'LOCHIA - น้ำคาวปลา', 'PNCHECKLIST - รายการตรวจ'],
  },
  NEWBORN: {
    menu: 'งาน PP / ทารกแรกเกิด',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ทารกแรกเกิด'],
    screen: 'บันทึกข้อมูลทารกแรกเกิด',
    note: 'บันทึกทารกทุกรายที่คลอดในหรือนอกสถานพยาบาล',
    keyFields: ['PID_BABY - ทะเบียนทารก', 'BIRTHWEIGHT - น้ำหนักแรกเกิด (กรัม)', 'APGAR1/APGAR5 - คะแนน APGAR', 'BREASTFEED - ให้นมแม่', 'CONGENITAL - ความพิการแต่กำเนิด'],
  },
  NEWBORNCARE: {
    menu: 'งาน PP / ทารกแรกเกิด',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ดูแลทารกหลังคลอด'],
    screen: 'บันทึกการดูแลทารกหลังคลอด',
    note: 'เยี่ยมทารกที่บ้านภายใน 7 วัน',
    keyFields: ['NBCVISITNO - ครั้งที่เยี่ยม', 'DATE_SERV - วันที่เยี่ยม', 'NBCCHECKLIST - รายการตรวจ', 'BREASTFEED - นมแม่'],
  },
  EPI: {
    menu: 'งาน PP / วัคซีน',
    path: ['งาน PCU', 'บันทึกวัคซีน / EPI'],
    screen: 'บันทึกการให้วัคซีน',
    note: 'บันทึกทุกครั้งที่ให้วัคซีน',
    keyFields: ['VACCINE - รหัสวัคซีน', 'LOTNO - เลข Lot', 'SERIALNO - เลข Serial', 'MANUF - ผู้ผลิต', 'PROVIDER - ผู้ให้วัคซีน'],
  },
  NUTRITION: {
    menu: 'งาน PP / โภชนาการ',
    path: ['งาน PCU', 'งานอนามัยแม่และเด็ก', 'ติดตามโภชนาการ/พัฒนาการเด็ก'],
    screen: 'บันทึกโภชนาการและพัฒนาการ',
    note: 'บันทึกน้ำหนัก-ส่วนสูงทุกครั้ง',
    keyFields: ['WEIGHT - น้ำหนัก (กก.)', 'HEIGHT - ส่วนสูง (ซม.)', 'NUTRITIONCODE - ภาวะโภชนาการ', 'DEVCODE - พัฒนาการ'],
  },
  SPECIALPP: {
    menu: 'งาน PP / บริการส่งเสริมป้องกัน',
    path: ['งาน PCU', 'บันทึก PP Special'],
    screen: 'บันทึกบริการส่งเสริมสุขภาพเฉพาะ',
    note: 'บันทึกบริการ PP ตามกลุ่มเป้าหมาย',
    keyFields: ['PPTYPE - ประเภทบริการ PP', 'DATE_SERV - วันที่', 'PROVIDER - ผู้ให้บริการ'],
  },
  COMMUNITY_ACTIVITY: {
    menu: 'งาน PP / งานชุมชน',
    path: ['งาน PCU', 'บันทึกกิจกรรมชุมชน'],
    screen: 'บันทึกกิจกรรมในชุมชน',
    note: 'บันทึกกิจกรรมสุขภาพในชุมชน',
    keyFields: ['ACTIVITYTYPE - ประเภทกิจกรรม', 'ACTIVITYDATE - วันที่กิจกรรม', 'NUMATT - จำนวนผู้เข้าร่วม'],
  },
  COMMUNITY_SERVICE: {
    menu: 'งาน PP / งานชุมชน',
    path: ['งาน PCU', 'บันทึกบริการสุขภาพในชุมชน'],
    screen: 'บันทึกบริการสุขภาพระดับบุคคลในชุมชน',
    note: 'บันทึกการให้บริการสุขภาพนอกสถานพยาบาล',
    keyFields: ['SERV_PLACE - สถานที่ให้บริการ', 'SERV_TYPE - ประเภทบริการ', 'DATE_SERV - วันที่'],
  },
  CARE_REFER: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'บันทึกการดูแลขณะส่งต่อ'],
    screen: 'บันทึก Refer Out — การดูแลขณะส่งต่อ',
    note: 'บันทึกการดูแลผู้ป่วยขณะส่งต่อ',
    keyFields: ['REFERID - เลขที่ Refer', 'CARE_TYPE - ประเภทการดูแล', 'REFERHOSP - รพ.ปลายทาง'],
  },
  CLINICAL_REFER: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'ประเมินทางคลินิก'],
    screen: 'บันทึก Refer Out — ประเมินทางคลินิก',
    note: 'บันทึกผลประเมินคลินิกก่อนส่งต่อ',
    keyFields: ['REFERID - เลขที่ Refer', 'CLINICTYPE - ประเภทการประเมิน', 'CLINICRESULT - ผล'],
  },
  DRUG_REFER: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'ยาที่ให้ระหว่างส่งต่อ'],
    screen: 'บันทึก Refer Out — ยา',
    note: 'บันทึกยาที่ให้ระหว่างส่งต่อ',
    keyFields: ['REFERID - เลขที่ Refer', 'DIDCODE - รหัสยา', 'AMOUNT - จำนวน'],
  },
  INVESTIGATION_REFER: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'ผลแล็บระหว่างส่งต่อ'],
    screen: 'บันทึก Refer Out — ผลตรวจห้องปฏิบัติการ',
    note: 'บันทึกผลตรวจก่อนส่งต่อ',
    keyFields: ['REFERID - เลขที่ Refer', 'LABTEST - รหัสการทดสอบ', 'LABRESULT - ผล'],
  },
  PROCEDURE_REFER: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'หัตถการระหว่างส่งต่อ'],
    screen: 'บันทึก Refer Out — หัตถการ',
    note: 'บันทึกหัตถการที่ทำก่อนส่งต่อ',
    keyFields: ['REFERID - เลขที่ Refer', 'PROCEDCODE - รหัส ICD-9-CM', 'PROCEDTYPE - ประเภท'],
  },
  REFER_HISTORY: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'ส่งต่อผู้ป่วย', 'ประวัติการส่งต่อ'],
    screen: 'บันทึกการส่งต่อ (Refer Out)',
    note: 'บันทึกการส่งต่อผู้ป่วยไปรพ.อื่น',
    keyFields: ['REFERID - เลขที่ Refer (unique)', 'REFERHOSP - รหัส รพ.ปลายทาง', 'REFERDATETIME - วันเวลาส่งต่อ', 'REFERCAUSE - เหตุผล', 'REFERTYPE - ประเภท (1=ฉุกเฉิน, 2=นัดหมาย)'],
  },
  REFER_RESULT: {
    menu: 'งานส่งต่อ (Refer)',
    path: ['งานผู้ป่วยนอก/ใน', 'รับ Refer In', 'บันทึกผลการรับ Refer'],
    screen: 'บันทึกผลการรับ Refer In',
    note: 'บันทึกเมื่อรับผู้ป่วย Refer มาจาก รพ.อื่น',
    keyFields: ['REFERID - เลขที่ Refer เดิม', 'REFERHOSP - รหัส รพ.ต้นทาง', 'RESULTDATETIME - วันเวลารับ', 'RESULT - ผลการรับ'],
  },
  DATA_CORRECT: {
    menu: 'ระบบจัดการข้อมูล',
    path: ['ตั้งค่า', 'แก้ไขข้อมูล 43 แฟ้ม'],
    screen: 'แฟ้มแก้ไขข้อมูล (Data Correct)',
    note: 'สำหรับแก้ไขข้อมูลที่ส่งออกผิดพลาด',
    keyFields: ['PID - ทะเบียนบุคคล', 'FILECODE - รหัสแฟ้มที่แก้ไข', 'FIELDNAME - ชื่อฟิลด์ที่แก้', 'OLDVALUE - ค่าเก่า', 'NEWVALUE - ค่าใหม่'],
  },
  POLICY: {
    menu: 'ตั้งค่าระบบ',
    path: ['ตั้งค่า', 'นโยบาย / POLICY'],
    screen: 'แฟ้มตามนโยบาย',
    note: 'ตรวจสอบกับผู้ดูแลระบบ / DBA',
    keyFields: ['POLICYCODE - รหัสนโยบาย', 'POLICYVALUE - ค่านโยบาย'],
  },
}

export function getHisGuide(fileName: string): HisGuide | null {
  const key = fileName.replace(/\.txt$/i, '').toUpperCase()
  return HIS_GUIDE[key] ?? null
}
